package game

SCREEN_WIDTH  :: 640
SCREEN_HEIGHT :: 360
TILE_SIZE     :: 16
TARGET_FPS    :: 60

PLAYER_SPEED   :: 120.0
GRAVITY        :: 600.0
JUMP_VELOCITY  :: -220.0
MAX_FALL_SPEED :: 400.0
MAX_JUMPS      :: 2

PLAYER_HITBOX_W :: 8
PLAYER_HITBOX_H :: 14

SPRITE_SRC_SIZE :: 16
SPRITE_DST_SIZE :: 16

ANIM_FRAME_TIME :: 0.12

DASH_SPEED         :: 800.0
DASH_DURATION      :: 0.25
DASH_COOLDOWN      :: 0.5
MAX_DASH_PARTICLES :: 64

COMPANION_SRC_SIZE   :: 32
COMPANION_OFFSET_X   :: 14.0
COMPANION_OFFSET_Y   :: 0.0
COMPANION_LERP_SPEED :: 10.0

COMPANION_ATTACK_COOLDOWN :: 2.0
COMPANION_ONESHOT_FPS     :: 12.0
COMPANION_DAMAGE          :: 21.0

// Player combat
PLAYER_MAX_HP :: 100.0

// Enemy – fireball
ENEMY_SRC_SIZE         :: 16
ENEMY_HITBOX_W         :: 12
ENEMY_HITBOX_H         :: 12
ENEMY_HP               :: 21.0
ENEMY_DAMAGE           :: 18.0
ENEMY_SPEED            :: 130.0
ENEMY_ATTACK_COOLDOWN  :: 4.0
ENEMY_ANIM_FPS         :: 12.0
MAX_ENEMIES            :: 32

// Damage flash
DAMAGE_FLASH_DURATION  :: 0.15
